title: Learn With Me
description: Tutorials and guides for computational software
collections:
  docs:
    output: true
    permalink: /:collection/:path/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
