title: Learn With Me
description: Tutorials and guides for computational software
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
navigation:
  - title: "Gaussian"
    url: "/_docs/gaussian/"
  - title: "ADF"
    url: "/_docs/adf/"
