title: Learn With Me
description: Tutorials and guides for computational software
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
nav:
  - title: "Gaussian"
    url: "/_docs/gaussian/"
    nav_order: 1
  - title: "ADF"
    url: "/_docs/adf/"
    nav_order: 2
